version: '3'

networks:
    nginx-php80-postgres:

services:

    # nginx
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./app:/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php80
            - postgresdb
        networks:
            - nginx-php80-postgres

    # php
    php80:
        build:
            context: ./
            dockerfile: ./php/Dockerfile
        container_name: php80
        ports:
            - "9000:9000"
        volumes:
            - ./app:/app
        networks:
            - nginx-php80-postgres

    # postgres
    postgresdb:
        image: postgres:11-alpine
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        container_name: postgresdb
        ports:
            - "5432:5432"
        volumes:
            - ./postgres:/var/lib/postgres
        restart: always # always restart unless stopped manually
        networks:
            - nginx-php80-postgres